server:
   tomcat:
     max-threads: 600
     max-connections: 200
     min-spare-threads: 300
     accept-count: 700

#LOGGING
logging:
    config: classpath:logback.xml

#spring config
spring:
    datasource:
      url: jdbc:mysql://125.65.83.240:3306/project?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: project
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        connection-test-query: SELECT 1
        validation-timeout: 3000
        connectionTimeout: 60000
        idle-timeout: 60000
        max-lifetime: 1800000
        maximum-pool-size: 15


mybatis:
    mapper-locations: classpath*:mapper/*.xml
    config: classpath:mybatis-config.xml